module.exports = {
  ascii: "Must contain only ASCII characters ",
  byte: "Must be in byte format",
  dataUri: "Must be in data uri format",
  magnetUri: "Must be in magnet uri format",
  dateTime: "Must be a date-time in RFC 3339 format",
  date: "Must be a date in ISO 8601 format",
  domainName: "Must be a valid domain name",
  hash: "Must be in hash format",
  hexColor: "Must be a valid hex color",
  mongoId: "Must be a valid Mongo ID",
  mobilePhone: "Must be a valid mobile phone",
  postalCode: "Must be a valid postal code",
  mimeType: "Must be a valid MIME type",
  email: "Must be in email format",
  isbn: "Must be in ISBN format",
  ipv4: "Must be in IP v4 format",
  ipv6: "Must be in IP v6 format",
  uri: "Must be in URI format",
  uuid: "Must be in UUID format"
};
